# Generated by Django 3.2.9 on 2021-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Lula', max_length=666)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('documento', models.CharField(max_length=666)),
                ('pode_votar', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
