# Generated by Django 3.2.9 on 2021-12-01 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesario',
            fields=[
                ('nome', models.CharField(default='Lula', max_length=666)),
                ('documento', models.CharField(max_length=666)),
                ('chave_de_acesso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
