# Generated by Django 3.2.9 on 2021-12-01 16:48

import Eleicao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=Eleicao.models.generate_election_id, max_length=6)),
            ],
        ),
    ]
